### ISSUE TITLE
Stopped working on Linux after last update

### ISSUE THREAD

**Issue by jdevine** [cuixiping/Save-Image-as-Type#24]
on Chrome linux Version 108.0.5359.124, gave new notification permissions. Nothing happens when trying to use the context menu options. Does not save, covert, or emit any error message. Is there a debugging step I should take? 

Has been working fine until yesterday. Stopped and started Chrome. Uninstalled and reinstalled extension. Still does not work.

**Comment by PhoenixEugene** [comment]
Same here.

**Comment by cuixiping** [comment]
Thanks for your feedback. I'll check it.
I tested on my Chrome 112 on windows and works well. I din't tested on Chrome linux yet.

**Comment by cuixiping** [comment]
It may be a chrome bug:  
[Issue 1271154: MV3 service worker broken after auto-update and manual refresh](https://bugs.chromium.org/p/chromium/issues/detail?id=1271154#c52)

You can try remove the extension and re-install from web store. 
[Save image as Type](https://chrome.google.com/webstore/detail/save-image-as-type/gabfmnliflodkdafenbcpjdlppllnemd)

**Comment by cuixiping** [comment]
The `offscreen  API` need Chrome 109+

I should do some work for lower versions.


[offscreen](https://developer.chrome.com/docs/extensions/reference/offscreen)	
Chrome 109+
MV3+

**Comment by cuixiping** [comment]
@jdevine @PhoenixEugene 
I have post a update to web store.  It's waiting reviewing.
You can try it again once you see the new version of 1.2.2
[Save image as Type](https://chrome.google.com/webstore/detail/save-image-as-type/gabfmnliflodkdafenbcpjdlppllnemd)

**Comment by cuixiping** [comment]
@jdevine  @PhoenixEugene 
I have post a update to web store. It's pending review.
You can try it again once you see the new version of 1.2.3
It works well from chrome 88 to 115 on win 11 as I tested on browserstack.

**Comment by jdevine** [comment]
Yes, thank you! Works again on my old machine (which is kept back to Chrome 108 on linux for access to old packages)
