### ISSUE TITLE
Add french translation

### ISSUE THREAD

**Issue by twaiiiin** [cuixiping/Save-Image-as-Type#5]
Hi,

Here is a suggestion to add the french translations : 

**Save image as** : Enregistrer l'image sous
**Save as JPG** : Enregistrer au format JPG...
**Save as PNG** : Enregistrer au format PNG...
**Save as WEBP** : Enregistrer au format WEBP...
**View in store** : Afficher sur le store...

**Comment by cuixiping** [comment]
Thank you. I'll add French at next update.
